<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #333;
            max-width: 75rem;
            margin: 0 auto;
            padding: 2rem;
          }
          a {
            color: #0580F2;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          h1 {
            font-size: 2rem;
            margin-bottom: 0.5rem;
          }
          .description {
            font-size: 0.9rem;
            color: #666;
            margin-bottom: 2rem;
            background: #f8f9fa;
            padding: 1rem;
            border-radius: 4px;
          }
          table {
            border-collapse: collapse;
            width: 100%;
            margin-bottom: 2rem;
          }
          th {
            text-align: left;
            padding: 1rem;
            border-bottom: 2px solid #eee;
            font-weight: 600;
          }
          td {
            padding: 0.75rem 1rem;
            border-bottom: 1px solid #eee;
          }
          tr:hover td {
            background-color: #f8f9fa;
          }
          .footer {
            font-size: 0.8rem;
            color: #999;
            margin-top: 2rem;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <h1>XML Sitemap</h1>
        <div class="description">
          <p>
            This is an XML Sitemap, meant for consumption by search engines like Google or Bing.
            <br/>
            You can find more information about XML sitemaps on <a href="https://sitemaps.org">sitemaps.org</a>.
          </p>
        </div>
        
        <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
          <h2>Sitemap Index</h2>
          <table>
            <thead>
              <tr>
                <th>Sitemap</th>
                <th>Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                <tr>
                  <td>
                    <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                  </td>
                  <td>
                    <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </xsl:if>
        
        <xsl:if test="count(sitemap:urlset/sitemap:url) &gt; 0">
          <h2>Sitemap Content</h2>
          <table>
            <thead>
              <tr>
                <th>URL</th>
                <th>Last Modified</th>
                <th>Change Frequency</th>
                <th>Priority</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <tr>
                  <td>
                    <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                  </td>
                  <td>
                    <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:changefreq"/>
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:priority"/>
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </xsl:if>
        
        <div class="footer">
          Generated by Collegeskhojo ( Wewon Academy )
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
